name: GitHub Pages

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: "0 0 * * 0"

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v6
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - uses: astral-sh/setup-uv@v8.1.0
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install texlive-latex-extra texlive-fonts-recommended dvipng cm-super
          uv sync --extra full --extra docs
        
      - name: Run notebook
        run: |
          cd examples
          uv run jupyter nbconvert --to html --execute *.ipynb
          cd ..

      - name: Build documentation
        run: |
          cd docs
          mv Makefile.gh_pages Makefile
          cp ../examples/GWMemory.ipynb ./example.ipynb
          cp ../examples/Comparison.ipynb ./comparison.ipynb
          uv run make clean
          uv run make html
          cd ../
          touch _gh-pages/latest/html/.nojekyll
          rm -r docs
          mv _gh-pages/latest/html docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
